### ISSUE TITLE
[BUG]使用数据坞五合一会莫名其妙卡住，有时候是无法识别屏幕，有时候是计时停止，且不报错

### ISSUE THREAD

**Issue by QuerXD** [ok-oldking/ok-wuthering-waves#101]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=)

描述错误:
使用数据坞五合一会莫名其妙卡住，有时候是无法识别屏幕，有时候是计时停止，且不报错

复现步骤 按照以下步骤复现行为：

1. 点击 数据坞五合一’

截图 :
如果适用，添加截图以帮助解释您的问题。

是否必现:
小概率

录屏:
最好有录屏上传QQ频道

脚本软件版本：
[如]2.11正式版

windows操作系统:
[例如] Windows 11 Pro 23H2 22631.3593

上传日志:
将脚本安装目录的logs,screenshots打包上传附件
[BUG.zip](https://github.com/user-attachments/files/16739643/BUG.zip)

**Comment by ok-oldking** [comment]
更新最新试试
