### ISSUE TITLE
[BUG]龙凤队（今汐/长离组队）今汐E4不喷

### ISSUE THREAD

**Issue by qwe4559999** [ok-oldking/ok-wuthering-waves#103]
描述错误:
龙凤队（今汐/长离组队）今汐E4不喷

复现步骤 按照以下步骤复现行为：

1.开启自动战斗，使用长离+今汐+奶配队
2.找到任意怪物，触发自动战斗
3.看到错误

截图 :
此为测试打无妄者/角时发现的不喷E4情况
第一个录屏38s时（e4亮了好久都没按）
![屏幕截图 2024-08-25 205219](https://github.com/user-attachments/assets/3ebcf2e7-345a-407d-8bca-da11731ce71f)

第二个录屏14s时可以观察到不喷e4（秒切维里奈，似乎按了e4但是没按出来）
![屏幕截图 2024-08-25 205009](https://github.com/user-attachments/assets/183bca36-a406-4863-9f92-a6a7ca689462)

是否必现:
是，此情况在更新最新版本后出现，0.2.10时未发现此情况

录屏:
见QQ频道8月25日20:55左右消息

脚本软件版本：
0.2.16

windows操作系统:
Windows 11 家庭中文版 23H2 22631.4037

上传日志:

[logs.zip](https://github.com/user-attachments/files/16740330/logs.zip)

**Comment by ok-oldking** [comment]
Release v0.2.17

**Comment by qwe4559999** [comment]
感谢
