### ISSUE TITLE
[BUG]依旧是刷辉莹军势

### ISSUE THREAD

**Issue by shjx1996** [ok-oldking/ok-wuthering-waves#11]
描述错误:
图标和卡主的位置见下截图

截图 :
![image](https://github.com/user-attachments/assets/70cd919f-44b9-4d39-b2d6-6cca245bfc7a)
![image](https://github.com/user-attachments/assets/ca48c6da-120c-47f7-8d08-ad32315a7e6d)

脚本软件版本：
V0.1.12

windows操作系统:
 [例如] Windows 11 Pro 23H2 22631.3593

模拟器版本:
 [如使用模拟器]MuMu模拟器12 V3.8.25 (2927)

上传日志:
将脚本安装目录的logs,screenshots,config,click_screenshots打包上传附件

**Comment by ok-oldking** [comment]
我右边那个传送点没开, 第一张图麻烦用截图测试截一张上传

**Comment by shjx1996** [comment]
已经好了，需要将错位信标放在BOSS声痕中间，偏一点就会变成我截图的顺序

**Comment by ok-oldking** [comment]
应该跟顺序无关是按照匹配度排序的
