### ISSUE TITLE
本期深塔右

### ISSUE THREAD

**Issue by lavender7410** [ok-oldking/ok-wuthering-waves#110]
卡卡羅 吟霖 隨便搭個散華 拿來疊BUFF

其他沒啥問題 就是卡卡羅基本開R就切了 或者只打一次死告 沒了 吟霖跟散華都佔場過久
感覺腳本好像沒啥主C觀念 就是猛打 XD

**Comment by lavender7410** [comment]
而且時常還會有發呆的時候 直接被哀叫鳥抓死 噴死 羽毛射死之類的 更別說如果只用卡卡羅+吟霖了 直接躺地上

**Comment by lavender7410** [comment]
FPS穩定60

**Comment by lavender7410** [comment]
開場等了三秒 然後直接放大 導致BOSS都沒下來就直接空招 一直切 是不能麻煩大大優化一下呢 感恩^_^

**Comment by lavender7410** [comment]
看得我腦溢血 等更新~"~

**Comment by qwe4559999** [comment]
脚本不支持卡卡罗 作者也没做适配 不知道是不是因为卡卡罗有延奏动画导致不好识别

**Comment by lavender7410** [comment]
> 劇本不支持卡卡羅作者也沒做修改不知道是不是因為卡卡羅有延演動畫導致不好識別

我用吟霖 散華 白芷也是一樣 各種被抓 被羽毛噴死

**Comment by lavender7410** [comment]
作者好像不怎麼看0.0

**Comment by lavender7410** [comment]
而且完全看不懂作者寫的輸出手法怎麼改

**Comment by ok-oldking** [comment]
看常见问题

**Comment by lavender7410** [comment]
> 看常見問題

常見問題?

**Comment by lavender7410** [comment]
> 看常見問題

你哪裡有常見問題的呢 卡卡羅

**Comment by lavender7410** [comment]
![image](https://github.com/user-attachments/assets/eb4066b6-0bf6-458f-842b-4e2e143da63b)

**Comment by lavender7410** [comment]
> 看常见问题

![image](https://github.com/user-attachments/assets/577c767e-a178-4a96-a300-80f3cd794006)

**Comment by ok-oldking** [comment]
更新链接了

**Comment by lavender7410** [comment]
> 更新链接了

不是 哥們 你這跟我的問題真的有關連麼 0.o
