### ISSUE TITLE
[BUG]3个关于大世界自动战斗问题的反馈

### ISSUE THREAD

**Issue by hyz-hyz** [ok-oldking/ok-wuthering-waves#113]
1白芷的连招不会放乌龟声骸,而维里奈就会放
2新英雄相里要无法识别,会识别成今汐/忌炎/漂泊者/折枝,详见图1
3有时候自动战斗的按钮会无故取消,发生的场景是晚上用自动锄大地工具,白天查看时发现自动战斗取消导致角色死亡,日志见附件23,晚上挂机锄大地的时间是2024-09-09 04:10:22,868到2024-09-09 14:14:02,501,出问题的时间是在此期间,根据自动锄大地工具的日志显示,大约是在2024-09-09 12:34:38,821死亡的,推测是在这个时间点附近产生的取消自动战斗问题,可能会用到自动锄大地工具的日志,也一并附上,见附件4,如不需要请忽略
![图1](https://github.com/user-attachments/assets/733aef13-265d-4c91-9e04-6660747f0e8f)
[Uploading ok-script.log…]()
[ok-script_error.log](https://github.com/user-attachments/files/16927043/ok-script_error.log)
[Uploading lanrenmingchaoai.log…]()

**Comment by hyz-hyz** [comment]
日志附件好像上传失败了,重新打压缩包上传
[log.zip](https://github.com/user-attachments/files/16927091/log.zip)

**Comment by ok-oldking** [comment]
最新测试版已经支持乡里要
白芷声骸是要协奏快满才放 配合今汐
