### ISSUE TITLE
[Enhancement]请问这个后台键鼠是如何实现的?用win32 api吗? 还是有特别的处理?想学习研究一下

### ISSUE THREAD

**Issue by beichen2023** [ok-oldking/ok-wuthering-waves#118]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement)

描述:

**Comment by ok-oldking** [comment]
看代码
