### ISSUE TITLE
[BUG]聲骸5合1  1c 聲骸主詞條無法辨認

### ISSUE THREAD

**Issue by QAQDDDDD** [ok-oldking/ok-wuthering-waves#121]
描述错误:

在1600x900 文字簡體中文環境下
使用聲骸5合1選項 4c與3c聲骸都能正常辨別合成直到要合成1c 就會出現這個問題

复现步骤 按照以下步骤复现行为：
1. 点击 5合1聲骸
2. 擺上5個1c聲骸
3. 跳出無法識別聲骸主詞條屬性

截图 :
如果适用，添加截图以帮助解释您的问题。

是否必现:
每次都會

录屏:
最好有录屏上传QQ频道

脚本软件版本：
[如]0.365

windows操作系统:
 Windows 11 

上传日志:
将脚本安装目录的logs,screenshots打包上传附件

**Comment by QAQDDDDD** [comment]
我嘗試了一下遇到1c鳴泣戰士時攻擊主詞條就沒辦法識別

**Comment by ok-oldking** [comment]
等1.3官方合成看看
