### ISSUE TITLE
掛晚上月卡出現之後不會自動點擊繼續的問題

### ISSUE THREAD

**Issue by jjasoncool** [ok-oldking/ok-wuthering-waves#122]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement)

描述:如標題

月卡出現之後
戰鬥就終止了(刷 BOSS聲骸)

**Comment by ok-oldking** [comment]
现在只能在刷世界boss时可以跳过

**Comment by jjasoncool** [comment]
> 现在只能在刷世界boss时可以跳过

對，就是刷世界BOSS卡住的

**Comment by jjasoncool** [comment]
@ok-oldking 這個會後續改進嗎?
