### ISSUE TITLE
[Enhancement]希望支持识别手柄的UI

### ISSUE THREAD

**Issue by bddyzpm** [ok-oldking/ok-wuthering-waves#124]
并不是要支持手柄，只是用手柄之后UI会有变化，导致遇到敌人不会自动战斗，需要动一下鼠标切换成键鼠才生效

**Comment by ok-oldking** [comment]
我没手柄  截个图看看

**Comment by bddyzpm** [comment]
![QQ截图20240928224519](https://github.com/user-attachments/assets/0d694462-9500-4bbc-b277-e2da1844b344)

**Comment by ok-oldking** [comment]
不行 差太多了

**Comment by liuqq58** [comment]
那能不能添加一个识别，避免因为识别到手柄操作界面然后报错导致自动停止或者退出？
