### ISSUE TITLE
[BUG] 问一下，为什么窗口化之后，运行打4C会直接按ESC进入菜单界面，然后就开始报错了，而不是按F2找4c副本

### ISSUE THREAD

**Issue by Canda15** [ok-oldking/ok-wuthering-waves#126]
下两个图是当时报错的提示。窗口分辨率为1600*900
![图片](https://github.com/user-attachments/assets/16b00e8e-b5ad-4388-9a8e-9cd3fc76cb35)
![图片](https://github.com/user-attachments/assets/73c1656d-c1a9-4c13-8bc2-fde2425a8871)

解决方法是窗口化后，把ww-ok关了，重开就能正常运行了。

还有一个问题就是我看文档里写了1280x720不支持，但是我这样重启后1280x720也能正常用。1280x720不支持是在哪方面不支持能说一下吗

这个问题是1个月前我入坑鸣潮用ok-ww就发现的，当时用的正式版。目前用测试版还是能复现

**Comment by ok-oldking** [comment]
截图看下分辨率对不对, 鸣潮有bug
