### ISSUE TITLE
[BUG]每次启动都会出现大片红色报错无法启动

### ISSUE THREAD

**Issue by memgkong** [ok-oldking/ok-wuthering-waves#128]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/blob/master/README_cn.md#出现问题请检查)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=)

描述错误:
[请清晰简洁地描述错误是什么]
每次启动都会有如图的大片报错，然后更新或者启动会用非常长的时间或者干脆无法启动
![image](https://github.com/user-attachments/assets/431aedf6-b7f2-49a4-8254-c9c4bdeae9f7)

复现步骤 按照以下步骤复现行为：

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
如果适用，添加截图以帮助解释您的问题。

是否必现:
是/否/大概率/小概率
大概率
录屏:
最好有录屏上传QQ频道

脚本软件版本：
[如]1.1.1

windows操作系统:

版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎9/‎12
操作系统版本	22631.4169
体验	Windows Feature Experience Pack 1000.22700.1034.0

上传日志:
将脚本安装目录的logs,screenshots打包上传附件
[ok-ww.zip](https://github.com/user-attachments/files/17179081/ok-ww.zip)

**Comment by ok-oldking** [comment]
更新

**Comment by memgkong** [comment]
> 更新

就是更新不了我才发issue啊，每次都在这卡着
![image](https://github.com/user-attachments/assets/3ee7c0e6-88b6-4328-b04e-0c9224bd703a)
