### ISSUE TITLE
[BUG]聲骸5合1 3c 聲骸主詞條無法辨認

### ISSUE THREAD

**Issue by QAQDDDDD** [ok-oldking/ok-wuthering-waves#130]
在1600x900 文字簡體中文環境下
使用聲骸5合1選項 4c與聲骸都能正常辨別合成直到要合成3c 就會出現這個問題

复现步骤 按照以下步骤复现行为：

点击 5合1聲骸
擺上5個3c聲骸
跳出無法識別聲骸主詞條屬性
截图 :
![1727614698748](https://github.com/user-attachments/assets/3edb8495-be8f-46ee-8507-333bc450f446)

是否必现:
每次都會

脚本软件版本：
[如]0.3.82正式版

windows操作系统:
Windows 11

**Comment by ok-oldking** [comment]
更新
