### ISSUE TITLE
[BUG]声骇五合一的问题

### ISSUE THREAD

**Issue by MilchstraBe-Z** [ok-oldking/ok-wuthering-waves#132]
我也遇到了声骇五合一的问题 大概类似#131

描述错误:
 虽然设置了config但是在筛选界面只勾选“cost#”和“5星”两个选项，并且之后会直接进行融合

复现步骤 按照以下步骤复现行为：

1. 打开声骇五合一界面
2. 启动“声骇五合一”功能
3. 软件筛选声骇（只勾选“cost#”和“5星”两个选项）
4. 软件开始自动添加声骇进行融合

截图 :
![image](https://github.com/user-attachments/assets/9f1a5980-1000-476c-b4a2-01e4af3684f4)

是否必现:
是

脚本软件版本：
0.3.84 GPU(Nvidia RTX >= 2000)

windows操作系统:
Windows 11 IoT Enterprise LTSC 24H2 26100.1742
RTX4060 Laptop GPU

上传日志:
见附件log & screenshots
[logs.zip](https://github.com/user-attachments/files/17183232/logs.zip)
[screenshots.zip](https://github.com/user-attachments/files/17183233/screenshots.zip)

**Comment by Georgebillion** [comment]
更新到0.3.97后故障复现

**Comment by Georgebillion** [comment]
![image](https://github.com/user-attachments/assets/816c0b20-6e22-444f-a77e-b36943f3bd82)
合成2次必定报错

**Comment by Georgebillion** [comment]
[ok-script_error.log](https://github.com/user-attachments/files/17221551/ok-script_error.log)
@ok-oldking 麻烦作者看一下，这个是日志文件

**Comment by Georgebillion** [comment]
![15-45-52 959_Auto Echo Data Merge_original](https://github.com/user-attachments/assets/7b6a324a-b5b8-47e0-ae06-ce8f7040e560)
![15-47-48 495_Auto Echo Data Merge_original](https://github.com/user-attachments/assets/8cdc7671-9038-49aa-ba6f-fca18439c5c8)
