### ISSUE TITLE
[BUG] 鑒心不會施放共鳴解放

### ISSUE THREAD

**Issue by Jerryansu** [ok-oldking/ok-wuthering-waves#135]
描述错误:
自動戰鬥時，當共鳴解放滿能量，鑒心不會施放共鳴解放。

截图 :
![WindowsGraphicsCaptureMethod_2560x1440_title_None_Client-Win64-Shipping exe_2560x1440_658052_1_False_1727714629436 5786_original](https://github.com/user-attachments/assets/ed9dc3a7-b399-468c-86a3-547ed296304f)

是否必现:
是

脚本软件版本：
0.3.88

windows操作系统:
Windows 11 教育版 23H2 22631.4169

上传日志:
[logs.zip](https://github.com/user-attachments/files/17193630/logs.zip)
[screenshots.zip](https://github.com/user-attachments/files/17193631/screenshots.zip)

**Comment by Small-Ku** [comment]
貌似作者特地不讓他施放的，應該不算 Bug。
有更好的[出招策略](https://github.com/ok-oldking/ok-wuthering-waves/blame/c4aea960ba92606b5bcd0ffd97b339a43fda97d8/src/char/Jianxin.py#L8)還是建議開 PR 吧
