### ISSUE TITLE
[BUG]弃置声骸功能滚动错误导致重复识别声骸判断弃置条件引起的问题

### ISSUE THREAD

**Issue by Realmajia** [ok-oldking/ok-wuthering-waves#136]
描述错误:
4k显示器，2560x1440分辨率窗口化游戏。使用弃置声骸功能时可观察到在逐个选中识别一页声骸（约4行x6列范围）后，在滚动列表的动作中会较频繁的出线只滚动1-3行的情况。并且在完成该次非足量的滚动后，会从当前第一行开始重新识别声骸并判断弃置条件。
因为如前述原因只滚动了1-3行，会再次识别到之前已完成识别的声骸。如果该声骸不符合弃置条件，程序会照常运行。但若此时再次识别的声骸是已经被在上一页识别中新标定为弃置的声骸。则程序会识别到该声骸弃置按钮的点亮状态，并停止运作，同时给出错误通知：无法找到弃置按钮——Cant't find discard button!

复现步骤 按照以下步骤复现行为：

我当前有1600多只声骸，所以列表较为庞大，按照我上面描述的情况我已经观察到该情况并确定了报错出现的原因，也确认并全程观察程序运作情况复现了四次左右。

是否必现:
是

脚本软件版本：
v0.3.89

windows操作系统:
Windows 10 22H2 19045.4780

**Comment by jerrytang123** [comment]
同样问题，程序扫描完一页的声骸无法滚动页面，会一直点击屏幕中间的声骸。手动滚动页面后会产生，no discard button的报错

**Comment by Realmajia** [comment]
试用了3.93pre。弃置功能已正常运作。close

**Comment by ok-oldking** [comment]
更新94 改成直接合成了
