### ISSUE TITLE
[BUG] 刷大世界4C BOSS 無法執行

### ISSUE THREAD

**Issue by Jack-Chen-tw** [ok-oldking/ok-wuthering-waves#139]
描述错误:

點擊開始以後會彈出錯誤視窗
'FarmWorldBossTask' object has no attribute 'mouse_reset'

截图 :
![image](https://github.com/user-attachments/assets/58d1b9f1-d68b-489a-92fc-747a47ebef6b)
![image](https://github.com/user-attachments/assets/08b4a12e-e500-46c4-95f9-268e0126c98b)

是否必现:
是

脚本软件版本：
V0.3.90 正式版

windows操作系统:
Windows 11 家用 23H2 22631.4169

**Comment by ok-oldking** [comment]
更新
