### ISSUE TITLE
[BUG]聲骸丟棄

### ISSUE THREAD

**Issue by QAQDDDDD** [ok-oldking/ok-wuthering-waves#140]
描述錯誤:
在1900x900解析度視窗化模式下，我的聲骸數量達到1200多個，在進行滾動操作的過程中（約在10分之2或10分之3時），會出現錯誤。而且常出現滾動1排，不是預期的3-4排，導致重複檢測

然後更新後每次檢查都從1C開始，導致重複動作，無法檢查到3C或4C。即使上次啟用檢查過的聲響滿足條件保留，下次啟用功能時仍會偵測浪費大量時間

是否必現:
是

腳本軟體版本：
v0.3.96

Windows作業系統：
Windows 11

**Comment by ok-oldking** [comment]
更新
