### ISSUE TITLE
[BUG]更新v0.3.92-cpu后软件无法启动

### ISSUE THREAD

**Issue by Kakitoritay** [ok-oldking/ok-wuthering-waves#141]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/blob/master/README_cn.md#出现问题请检查)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=)

描述错误:
硬件是a卡6950xt，更新0.3.92后软件无法打开，重新下载cpu包后问题依旧，看了下报错提示是调用了n卡驱动

复现步骤 按照以下步骤复现行为：

截图 :
如果适用，添加截图以帮助解释您的问题。

是否必现:
是

录屏:
最好有录屏上传QQ频道

脚本软件版本：
0.3.92

windows操作系统:
[例如] Windows 11 Pro 23H2 22631.3593

上传日志:
[launcher_error.log](https://github.com/user-attachments/files/17219092/launcher_error.log)

**Comment by Kakitoritay** [comment]
更新0.3.94问题也是一样

**Comment by ok-oldking** [comment]
试试96
