### ISSUE TITLE
[BUG] 更新v0.3.92-cpu 后软件无法启动 

### ISSUE THREAD

**Issue by Canda15** [ok-oldking/ok-wuthering-waves#142]
AMD显卡，intel cpu。更新到[v0.3.97](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.3.97) 后，能启动了，但是启动非常慢，要等好久才能打开 OK-WW启动器。跟之前的版本差非常多。
#141 141

**Comment by ok-oldking** [comment]
v0.3.99 需要重新下载
