### ISSUE TITLE
[BUG]每次更新都现实缺少文件

### ISSUE THREAD

**Issue by sunshine7001** [ok-oldking/ok-wuthering-waves#146]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/blob/master/README_cn.md#出现问题请检查)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=)

描述错误:
[请清晰简洁地描述错误是什么]

复现步骤 按照以下步骤复现行为：

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
如果适用，添加截图以帮助解释您的问题。
![a2afd211f78fa688296a30b500852235](https://github.com/user-attachments/assets/972cc379-1868-42f6-a87a-c5cf8140ee60)

是否必现:
否

录屏:
最好有录屏上传QQ频道

脚本软件版本：
0.3.100

windows操作系统:
Windows 11 家庭中文版

上传日志:
将脚本安装目录的logs,screenshots打包上传附件

**Comment by ok-oldking** [comment]
不用管 新版已经屏蔽
