### ISSUE TITLE
亲爱的开发者，我还可以用旧版不需要下载依赖的版本吗？

### ISSUE THREAD

**Issue by AsukaSoryu0** [ok-oldking/ok-wuthering-waves#149]
我记得以前是不用下载像gpu版本几个g大小的文件，都是几十兆就可以了。现在的新版gpu依赖有什么好处吗？

**Comment by Small-Ku** [comment]
> ok-ww-Nvidia-GPU-full GPU完整版, 需要英伟达RTX2000显卡以上或部分10显卡, 最新显卡驱动, 不需要再下载依赖,
> ok-ww-CPU-full CPU完整版, 不需要再下载依赖,
> ok-ww-release 无依赖版, 安装后需要下载依赖
> ok-ww.zip zip压缩版, 无法解压7z的可以下载

看 Release notes, 記得 close issue

**Comment by ok-oldking** [comment]
源码运行
