### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lemonydrop** [ok-oldking/ok-wuthering-waves#15]
描述错误:
渊武在和今夕进行配对时自动战斗不会释放e（或许和其他角色一起也是这样？）

复现步骤 按照以下步骤复现行为：
渊武在和今夕进行配对时自动战斗不会释放e（或许和其他角色一起也是这样？）
大概是战斗逻辑的问题
脚本软件版本：
latest

**Comment by ok-oldking** [comment]
渊武是写的70级的逻辑, 退场自动E
