### ISSUE TITLE
[Enhancement]添加自动振刀

### ISSUE THREAD

**Issue by Walkersifolia** [ok-oldking/ok-wuthering-waves#156]
检测到黄色光圈自动振刀可行吗，自动闪避因为没有明显通用的提示，感觉有些难做了，但是黄色光圈和红光都是有的。但是这样就得大范围的截屏，看了眼项目文件发现都是小范围的截屏，不知道这样的话是否会误判或者影响性能。

**Comment by Walkersifolia** [comment]
https://github.com/DoctorReid/ZenlessZoneZero-OneDragon

**Comment by ok-oldking** [comment]
加不了
