### ISSUE TITLE
[BUG]自动传送过去就一直平a，不会切人

### ISSUE THREAD

**Issue by Yuanboy-1** [ok-oldking/ok-wuthering-waves#160]
描述错误:
4c都有带，切到相里要一直平a，游戏建位都是默认设置，

截图 :
![微信图片_20241019170630](https://github.com/user-attachments/assets/7a0fb0f6-bd42-410f-8655-a3cae18ac293)
![微信截图_20241019170659](https://github.com/user-attachments/assets/c094485b-60c6-4960-aecb-791b1701a5df)
![微信截图_20241019170721](https://github.com/user-attachments/assets/2cb8ded8-74f5-4cce-97b2-106d21af6877)

是否必现:
是

脚本软件版本：
0.3.113

windows操作系统:
Windows 10 专业版 22H2 19045.5011
[Desktop.zip](https://github.com/user-attachments/files/17444477/Desktop.zip)

**Comment by ok-oldking** [comment]
目前不能带两个奶
