### ISSUE TITLE
[BUG] 自动战斗 切换到今汐 不进行攻击

### ISSUE THREAD

**Issue by nightlye** [ok-oldking/ok-wuthering-waves#165]
版本：0.3.114正式版
配队：今汐、长离、守岸者
问题描述：
开启自动战斗后，在如上配队情况下，不会自动切换到今汐进行战斗，而是一直在长离和守岸者之间切换。此外一旦切到守岸者就只会不停平a

**Comment by cocoadi** [comment]
因为守岸者未定义

**Comment by nightlye** [comment]
> 因为守岸者 [ShoreKeeper.py](https://github.com/ok-oldking/ok-wuthering-waves/blob/master/src/char/ShoreKeeper.py)

意思是目前自动代打我只能用没有守岸者的队伍吗？

**Comment by ok-oldking** [comment]
应该是守岸人入场技有动画的问题， 有空改一下
