### ISSUE TITLE
[BUG]截图失败，无法启动

### ISSUE THREAD

**Issue by johnson50313** [ok-oldking/ok-wuthering-waves#169]
截图失败，无法启动
[logs.zip](https://github.com/user-attachments/files/17748712/logs.zip)
](![image](https://github.com/user-attachments/assets/5238c55f-0825-482b-8948-853a372121bd))

**Comment by johnson50313** [comment]
1.4.8一样无法

**Comment by ok-oldking** [comment]
更新最新
