### ISSUE TITLE
[BUG]自动战斗/拾取，会自己关闭

### ISSUE THREAD

**Issue by johnson50313** [ok-oldking/ok-wuthering-waves#172]
自动战斗/拾取，会自己关闭，右下角通知显示(after_sleep)

[logs.zip](https://github.com/user-attachments/files/17761372/logs.zip)

**Comment by windyshower** [comment]
我在打肉鸽的时候也发现自动战斗没一会就自己关闭了

**Comment by johnson50313** [comment]
更新版本，一样异常

**Comment by ok-oldking** [comment]
更新 不行的话在上传日志
