### ISSUE TITLE
[BUG]刷大世界4C卡在地图界面

### ISSUE THREAD

**Issue by Initializist** [ok-oldking/ok-wuthering-waves#173]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/blob/master/README_cn.md#出现问题请检查)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=)

描述错误:
开启刷大世界4C 程序执行到index after scrolling down 5 后就卡在地图界面了
复现步骤 按照以下步骤复现行为：
重复开始都会在index after scrolling down 5后停止后续操作
我选择的boss是第二个雷boss
截图 :
如果适用，添加截图以帮助解释您的问题。
![image](https://github.com/user-attachments/assets/92093a68-4f4a-478f-82ce-ca1ce3a6971c)
![image](https://github.com/user-attachments/assets/721e0176-b7e4-452d-8afd-4bcc6e583cd3)
![image](https://github.com/user-attachments/assets/856c1d13-62a2-4cd9-a55d-c715fbc2a685)

是否必现:
是

录屏:
最好有录屏上传QQ频道

脚本软件版本：
1.4.14

windows操作系统:
Windows 10 Pro 22H2

上传日志:
将脚本安装目录的logs,screenshots打包上传附件
[ok-script.log](https://github.com/user-attachments/files/17774873/ok-script.log)

**Comment by ok-oldking** [comment]
更新
