### ISSUE TITLE
希望可以设置快捷键来开启/关闭 自动战斗 功能

### ISSUE THREAD

**Issue by LiunianShuai** [ok-oldking/ok-wuthering-waves#181]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement)

描述:
软件的自动战斗功能很强，但角色容易暴毙，能否将自动战斗功能通过热键来启停，类似罗技鼠标宏那样，这样可以手动闪避/弹反，然后靠软件打输出，希望作者大大有空可以看看，万分感谢~

**Comment by harrellmaria668-cmyk** [comment]
> f9

你好，可以加一个自定义暂停键的功能吗？机械革命的笔记本，不知道为什么F9用不了。FN+F9可以正常改变键盘背光，但也不能暂停。谢谢！
