### ISSUE TITLE
[BUG]大世界4C报错：Auto combat error: Make sure to turn off effect that changes the game color, (Game Gammar/Nvidia AMD Game Filter/HDR) 

### ISSUE THREAD

**Issue by zkfpk6** [ok-oldking/ok-wuthering-waves#189]
请先挨个检查:
1.未开启HDR；
2.未开启蓝光护眼；
3.开启/关闭自动管理颜色；
4.已关闭运动模糊；
5.已开启视角重制；
6.已关闭英伟达APP，无滤镜等；
7.尝试过1080P窗口，2K全屏；

搜索现有ISSUE:
未发现。

描述错误:
1.大世界4C报错：Auto combat error: Make sure to turn off effect that changes the game color, (Game Gammar/Nvidia AMD Game Filter/HDR)，进入战斗时，角色会疯狂切换boss的锁定/非锁定状态，同时报此错误。有几率不报错但是疯狂切换boss的锁定/非锁定状态，打两下，发呆，周而复始。
2.副本4C正常，自动战斗不会发呆，也不会疯狂切换boss的锁定/非锁定状态。

复现步骤 按照以下步骤复现行为：
1.手动打死乌龟，哀声鹫，摩托车，并在其脚下放置信标；
2.回到脚本，配置对应大世界4C boss，开启脚本；
3.脚本打开书，并传送到信标处；
4.进入战斗，开始报错；

截图 :

是否必现:
是

录屏:

脚本软件版本：
1.4.55 CPU + GPU

windows操作系统:
Windows 11 家庭中文版 23H2 22631.4460

上传日志:
[logs.zip](https://github.com/user-attachments/files/18031285/logs.zip)

**Comment by ok-oldking** [comment]
上传截图

**Comment by zkfpk6** [comment]
> 上传截图
已录制相关视频，辛苦查看下

https://github.com/user-attachments/assets/d679a439-087c-4c19-aa20-59fe8b450b18

**Comment by ok-oldking** [comment]
screen shots 文件夹里的截图

**Comment by zkfpk6** [comment]
> screen shots 文件夹里的截图

![21-00-02 212_Farm World Boss(Must Drop a WayPoint on the Boss First)_boxed](https://github.com/user-attachments/assets/55825559-3a18-45c5-9b75-a2a093224bd1)
![21-00-02 212_Farm World Boss(Must Drop a WayPoint on the Boss First)_original](https://github.com/user-attachments/assets/3511033b-d2b2-49fc-96ad-2202a407c28d)
![21-07-21 748_click_resonance too long, breaking_boxed](https://github.com/user-attachments/assets/b93f30a4-5000-4530-a425-c26886996267)
![21-07-21 748_click_resonance too long, breaking_original](https://github.com/user-attachments/assets/14ad701e-d8dd-48e4-819e-486258c179cb)
如图

**Comment by ok-oldking** [comment]
v1.4.57

**Comment by zkfpk6** [comment]
> v1.4.57

已更新，目前问题依旧存在
![BitBltCaptureMethod_1920x1080_title_None_Client-Win64-Shipping exe_1920x1080_6162942_True_False_1733531151988 98_original](https://github.com/user-attachments/assets/0894c933-e66a-4a29-8ce6-27bc8e4c51b8)
