### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by ter-123** [ok-oldking/ok-wuthering-waves#190]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement)

描述:
解锁声骸，每次合成锁定的太多了，希望能有个解锁所有的功能

**Comment by ok-oldking** [comment]
等官方优化
