### ISSUE TITLE
[BUG]大世界4C报错：Auto combat error: Make sure to turn off effect that changes the game color, (Game Gammar/Nvidia AMD Game Filter/HDR) 

### ISSUE THREAD

**Issue by zkfpk6** [ok-oldking/ok-wuthering-waves#191]
请先挨个检查:
1.未开启HDR；
2.未开启蓝光护眼；
3.开启/关闭自动管理颜色；
4.已关闭运动模糊；
5.已开启视角重制；
6.已关闭英伟达APP，无滤镜等；
7.尝试过1080P窗口，2K全屏；
**8.已更新1.4.57**

搜索现有ISSUE:
未发现。

描述错误:
1.大世界4C报错：Auto combat error: Make sure to turn off effect that changes the game color, (Game Gammar/Nvidia AMD Game Filter/HDR)，进入战斗时，角色会疯狂切换boss的锁定/非锁定状态，同时报此错误。有几率不报错但是疯狂切换boss的锁定/非锁定状态，打两下，发呆，周而复始。
2.副本4C正常，自动战斗不会发呆，也不会疯狂切换boss的锁定/非锁定状态。

复现步骤 按照以下步骤复现行为：
1.手动打死乌龟，哀声鹫，摩托车，并在其脚下放置信标；
2.回到脚本，配置对应大世界4C boss，开启脚本；
3.脚本打开书，并传送到信标处；
4.进入战斗，开始报错；

截图 :
![BitBltCaptureMethod_1920x1080_title_None_Client-Win64-Shipping exe_1920x1080_6162942_True_False_1733531151988 98_boxed](https://github.com/user-attachments/assets/b0404541-898c-4508-bcb8-84b935a8bd10)

是否必现:
是

录屏:

脚本软件版本：
1.4.55 CPU + GPU

windows操作系统:
Windows 11 家庭中文版 23H2 22631.4460

**Comment by zkfpk6** [comment]
补充
![BitBltCaptureMethod_1920x1080_title_None_Client-Win64-Shipping exe_1920x1080_6162942_True_False_1733531533949 1323_boxed](https://github.com/user-attachments/assets/0968ff2f-e27f-4e2e-a148-ad9f5f1c72fd)

**Comment by ok-oldking** [comment]
自动更新的有点问题, 重新下载试试
