### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by huojieren** [ok-oldking/ok-wuthering-waves#195]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/blob/master/README_cn.md#出现问题请检查)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=)

描述错误:
每个版本都出现"Fetch remote version error!“，无论使用哪一个源，无论是否开启代理

截图 :
![image](https://github.com/user-attachments/assets/4e9eeee8-5f9c-4f8a-ac19-004be8e4fbc9)

是否必现:
是

脚本软件版本：
v1.4.58

windows操作系统:
Windows 11 专业版 23H2 22631.4602

上传日志:
[ok-ww.zip](https://github.com/user-attachments/files/18162724/ok-ww.zip)

**Comment by eterlan** [comment]
之前我也有，把gitconfig东西都注释就行了

**Comment by huojieren** [comment]
> 之前我也有，把gitconfig东西都注释就行了

请问gitconfig这部分在哪里呢，注释掉后是可以正常更新还是直接跳过更新了呢

**Comment by eterlan** [comment]
> > 之前我也有，把gitconfig东西都注释就行了
> 
> 请问gitconfig这部分在哪里呢，注释掉后是可以正常更新还是直接跳过更新了呢

可以百度一下的其实, `C:\Users\xxx\.getconfig` xxx是你的用户名

**Comment by huojieren** [comment]
> > > 之前我也有，把gitconfig东西都注释就行了
> > 
> > 请问gitconfig这部分在哪里呢，注释掉后是可以正常更新还是直接跳过更新了呢
> 
> 可以百度一下的其实, `C:\Users\xxx\.getconfig` xxx是你的用户名

感谢，我以为是要修改脚本软件里的gitconfig。测试之后应该是代理设置的问题，把.gitconfig中有关proxy的项全部注释掉之后就正常了。
