### ISSUE TITLE
[BUG]更新问题v1.4.78未解决

### ISSUE THREAD

**Issue by FV4005-X** [ok-oldking/ok-wuthering-waves#196]
描述错误:
[请清晰简洁地描述错误是什么]
点击检查更新按钮，会提示报错，拉取不到版本列表
![image](https://github.com/user-attachments/assets/f92d762f-0675-4ce1-92c5-e0e185216bb4)

复现步骤 按照以下步骤复现行为：

1. 打开 okww
2. 打开 关于
3. 点击 检查更新，无法获取列表，换更新源也无法解决问题
4. 点击 目标版本，无法退版本

截图 :
![image](https://github.com/user-attachments/assets/76ffb3d8-73de-445b-96af-9b971d44bb53)

是否必现:
是

脚本软件版本：
1.4.77

windows操作系统:
Windows 11 专业版 23H2 22631.4602

上传日志:
[ok-script.log](https://github.com/user-attachments/files/18264864/ok-script.log)

**Comment by FV4005-X** [comment]
关掉程序后，再次打开okww，程序无法打开，报错截图如下：
![image](https://github.com/user-attachments/assets/deb8b009-7236-4a78-88da-723101a83871)

**Comment by FV4005-X** [comment]
该问题在v1.4.78中未解决

**Comment by ok-oldking** [comment]
删除重下

**Comment by FV4005-X** [comment]
![image](https://github.com/user-attachments/assets/5a6ee894-ff9c-49a4-96a1-6ebf6e4a3764)
![image](https://github.com/user-attachments/assets/65ab18b7-1c75-4d5a-a9d5-679ce26d613d)
重下未解决。

点击更新版后，再次打开如下图：
![image](https://github.com/user-attachments/assets/9315bb45-7287-47ec-b5be-2df9a12a8d09)

**Comment by ok-oldking** [comment]
最新版也能更新吗? 上传下日志

**Comment by ok-oldking** [comment]
https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v1.4.79

**Comment by FV4005-X** [comment]
已解决√

**Comment by FV4005-X** [comment]
111
