### ISSUE TITLE
[BUG] 刷角的时候，出声骸了但识别不出来

### ISSUE THREAD

**Issue by kunkun9527** [ok-oldking/ok-wuthering-waves#2]
如题。

战斗正常进行，但有时候角的声骸爆在了屏幕的角落，角色的视角自动转了几圈，但没识别出来。

我建议减小每次视角转动的角度，从而更容易找到声骸。

**Comment by ok-oldking** [comment]
正常, 后台操作没法360度找, 多刷几次
