### ISSUE TITLE
[提问] 请问下assets下的png图片拿什么工具截的

### ISSUE THREAD

**Issue by qhhuang** [ok-oldking/ok-wuthering-waves#22]
只剩了需要的的图标 剩下全部都是白色的
我看ok-script里好像没有

**Comment by qhhuang** [comment]
有没有相关的gui工具，我想添加新的图片 发现[ok-wuthering-waves]项目里好像没有，okscript那个我找不到怎么单独启动GUI界面。 另外我在win下开发的时候template_matching中 'coco_feature_json': os.path.dirname(os.path.abspath(__file__)) + "/assets/_annotations.coco.json", 这个路径是这样填的。按项目中的os.path.join('assets', '_annotations.coco.json')会去引用python所在的地址。。。

**Comment by ok-oldking** [comment]
working dir是不是项目根目录

**Comment by ok-oldking** [comment]
https://app.roboflow.com/test-7ruyi/ww-jamcc/25
