### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cock-Doer** [ok-oldking/ok-wuthering-waves#24]
描述错误:
[请清晰简洁地描述错误是什么]

复现步骤 按照以下步骤复现行为：

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
如果适用，添加截图以帮助解释您的问题。

脚本软件版本：
[如]1.1.1

windows操作系统:
 [例如] Windows 11 Pro 23H2 22631.3593

模拟器版本:
 [如使用模拟器]MuMu模拟器12 V3.8.25 (2927)

上传日志:
将脚本安装目录的logs,screenshots,config,click_screenshots打包上传附件

**Comment by Cock-Doer** [comment]
能加一个 断线自动重连吗 ，或者任务失败直接 可以重启游戏 。重来

**Comment by ok-oldking** [comment]
加不了
