### ISSUE TITLE
[BUG]win10 运行一段时间后关闭，会出现关不干净，有残留

### ISSUE THREAD

**Issue by deYangar** [ok-oldking/ok-wuthering-waves#26]
描述错误:
win10 运行一段时间后关闭，会出现关不干净，任务栏会残留，但是双击任务栏的图标打不开，重新打开会提示已存在一个实例，只能在任务管理里关掉后再开

复现步骤 按照以下步骤复现行为：

目前不清楚百分百触发流程。但是
1、只打开，不运行任务，关掉，不会有问题
2、运行任务不长，10来秒，好像也不会有问题
3、运行自动战斗任务，5分钟左右就会触发

截图 :
![image](https://github.com/user-attachments/assets/41c104dd-423f-4cd5-bce6-18fcc0b323a0)

脚本软件版本：
v0.1.21，v0.1.33都有。是今天0.1.21升级的时候发现这个问题的，因为无法升级，关不掉后台。然后升级0.1.33后也有

windows操作系统:
Windows 10 专业工作站版 22H2 19045.4529

模拟器版本:
PC端

上传日志:
[configs.zip](https://github.com/user-attachments/files/16377937/configs.zip)
[logs.zip](https://github.com/user-attachments/files/16377936/logs.zip)

**Comment by ok-oldking** [comment]
能不能装下python 命令行跑一下, 点退出后退不出去, 用命令行ctrl+c, 会dump出线程

**Comment by zxygzxy** [comment]
win11也有这个问题，v0.1.45

**Comment by ok-oldking** [comment]
再试试最新版会不会

**Comment by deYangar** [comment]
> 再试试最新版会不会

0.1.67已经不会复现了
