### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FateYak** [ok-oldking/ok-wuthering-waves#30]
描述错误:
[请清晰简洁地描述错误是什么]
自动战斗时切换游戏内esc/f1/f2/f3/f4窗口

复现步骤 按照以下步骤复现行为：
自动战斗/刷4c

截图 :
如果适用，添加截图以帮助解释您的问题。

是否必现:小概率
是/否/大概率/小概率

录屏:
最好有录屏上传QQ频道

脚本软件版本：0.1.33

[如]1.1.1

windows操作系统:
版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2023/‎1/‎28
操作系统版本	22631.3880
序列号	PF2QFTG0
体验	Windows Feature Experience Pack 1000.22700.1020.0

 [例如] Windows 11 Pro 23H2 22631.3593

上传日志:
![Uploading 12-48-53.109_resolution_error_original.png…]()

将脚本安装目录的logs,screenshots打包上传附件

**Comment by ok-oldking** [comment]
不太明白 频道里上传录屏
