### ISSUE TITLE
[BUG]提前退出+声骸捡不到

### ISSUE THREAD

**Issue by MosEleven** [ok-oldking/ok-wuthering-waves#32]
描述错误:
提前退出：大概率发生
漏检声骸：小概率发生

脚本软件版本：
v0.1.33
屏幕2k分辨率，游戏设置1080P全屏
系统Win10 21H2

上传日志:
将脚本安装目录的logs,screenshots打包上传附件
[bug反馈-提前退出.zip](https://github.com/user-attachments/files/16400255/bug.-.zip)

**Comment by ok-oldking** [comment]
先看下常见问题

**Comment by MosEleven** [comment]
> 先看下常见问题

看过了，杀毒软件白名单都添加了，软件更新了，还是这样，才发的issue
我看它error日志抛的ok.task.TaskExecutor.WaitFailedException，是超时吗，可能是什么原因导致的？

**Comment by ok-oldking** [comment]
能不能流畅60或者30fps稳定运行游戏

**Comment by ok-oldking** [comment]
[Release v0.2.1](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.2.1)
