### ISSUE TITLE
[BUG]停住不按技能不切人

### ISSUE THREAD

**Issue by zxygzxy** [ok-oldking/ok-wuthering-waves#33]
描述错误:会莫名其妙的停住不按技能也不切人然后被打死
[请清晰简洁地描述错误是什么]

复现步骤 按照以下步骤复现行为：没看到这个在哪

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
如果适用，添加截图以帮助解释您的问题。

是否必现:是
是/否/大概率/小概率

录屏:
最好有录屏上传QQ频道

脚本软件版本：v0.1.45
[如]1.1.1

windows操作系统:版本	Windows 11 家庭中文版
版本号	23H2
操作系统版本	22631.3880
体验	Windows Feature Experience Pack 1000.22700.1020.0
[logs.zip](https://github.com/user-attachments/files/16400614/logs.zip)

 [例如] Windows 11 Pro 23H2 22631.3593

上传日志:
将脚本安装目录的logs,screenshots打包上传附件

**Comment by ok-oldking** [comment]
先看下常见问题

**Comment by zxygzxy** [comment]
> 先看下常见问题

我忘了之前调了镜头设置，现在有个问题，之前的初始设置已经不记得了，官方也没有还原默认的选项，应该调到多少有建议吗作者大大

**Comment by ok-oldking** [comment]
镜头只有第一个选项, 保证按鼠标中键能回正就行了
