### ISSUE TITLE
[BUG]雪豹自动战斗逻辑问题

### ISSUE THREAD

**Issue by 963606242** [ok-oldking/ok-wuthering-waves#34]
描述错误:
雪豹在开启自动战斗后只会A、E
完全不使用声骸技能、大招、共鸣回路

是否必现:
是

录屏:
最好有录屏上传QQ频道

脚本软件版本：
0.1.43

windows操作系统:
Windows 11 Pro 23H2 22631.3958

**Comment by ok-oldking** [comment]
短期内没计划支持雪豹
