### ISSUE TITLE
大佬可以研究一下做一个类似激战2的路径插件工具吗？

### ISSUE THREAD

**Issue by kof8855** [ok-oldking/ok-wuthering-waves#35]
激战2的这个插件开源地址是
https://github.com/BoyC/GW2TacO

原理就是在游戏的窗口内添加一层图层作为遮罩

路径的效果是这样，如果能弄一个这样的工具出来，大世界跑图锄地就方便很多
https://www.bilibili.com/video/BV1qX4y1C7qa
![image](https://github.com/user-attachments/assets/a2c2bbb5-d3f2-4cc2-965a-98dc7278e5fc)

**Comment by ok-oldking** [comment]
目前没计划添加更强的功能
