### ISSUE TITLE
[BUG]开自动战斗后，也不自动战斗

### ISSUE THREAD

**Issue by riandaline** [ok-oldking/ok-wuthering-waves#37]
请先挨个检查,[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

描述错误:
开自动战斗，没有自动战斗

复现步骤 按照以下步骤复现行为：
开启【实时触发】【自动战斗】
开启刷大世界4c声骸
传送到boss位置后，站着不动

截图 :
![WindowsGraphicsCaptureMethod_1920x1080_title_None_Client-Win64-Shipping exe_1920x1080_331358_1_False_boxed](https://github.com/user-attachments/assets/f7c07fff-b0cd-41c3-a968-4027d204c6f5)
分辨率1920*1080全屏

是否必现:
是

录屏:
最好有录屏上传QQ频道

脚本软件版本：
0.1.46

windows操作系统:
 Windows 10 21H2 19044.4651

上传日志:
[log.zip](https://github.com/user-attachments/files/16401966/log.zip)

**Comment by riandaline** [comment]
是否是根据血条颜色值判断的？如果是，可否将颜色值放到配置文件中，做成可配置的

**Comment by ok-oldking** [comment]
看下设置改建 不能用鼠标侧键
