### ISSUE TITLE
[BUG]提前结束任务并关闭软件无法正常关闭后台进程，强制关闭进程后会生成大量log

### ISSUE THREAD

**Issue by KitaharaHaru** [ok-oldking/ok-wuthering-waves#4]
描述错误:
提前暂停并结束未达指定次数的世界boss任务，并在第一个页面手动关闭2个触发器后叉掉软件，软件并未正常关闭，持续后台运行，并且内存占用量达到1G+，手动结束进程后获得669M log文件

任务栏无软件图标，在任务栏折叠图标里持续存在，无法执行任何操作

复现步骤 按照以下步骤复现行为：

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
无

脚本软件版本：
0.1.8

windows操作系统:
 Windows 11 家庭版 23H2 22631.3880

上传日志:
将脚本安装目录的logs,screenshots,config,click_screenshots打包上传附件
File size too big: 25 MB are allowed, 180 MB were attempted to upload.
已上传Q频

**Comment by ok-oldking** [comment]
已经尝试改了下 看看会不会复现
