### ISSUE TITLE
[BUG]很多声骸因为视角看不到无法拾取能否添加一个打完结束后再原地视角旋转360°检测声骸呢

### ISSUE THREAD

**Issue by Apcsw** [ok-oldking/ok-wuthering-waves#40]
请先挨个检查,[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

描述错误:
[请清晰简洁地描述错误是什么]

复现步骤 按照以下步骤复现行为：

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
如果适用，添加截图以帮助解释您的问题。

是否必现:
是/否/大概率/小概率

录屏:
最好有录屏上传QQ频道

脚本软件版本：
[如]1.1.1

windows操作系统:
[例如] Windows 11 Pro 23H2 22631.3593

上传日志:
将脚本安装目录的logs,screenshots打包上传附件

**Comment by ok-oldking** [comment]
后台没法360

**Comment by T1de2077** [comment]
可以利用重置镜头扫一遍 人物转一下 按一下重置镜头就可以扫了
