### ISSUE TITLE
[BUG]版本号0.1.49之后，添加了快捷键强制验证的选项，导致游戏镜头过几秒强制回正，有解决办法吗？

### ISSUE THREAD

**Issue by q406744724** [ok-oldking/ok-wuthering-waves#41]
描述错误:
使用版本号0.1.49及之后的版本，打开自动战斗，过几秒种游戏镜头强制回正，影响游戏操作，无论强制验证按键是否开启都会触发。
我已回退至0.1.47，这个版本没有如此问题，希望能得到大佬得修复。

复现步骤 按照以下步骤复现行为：
只要使用0.1.49及之后的版本且打开自动战斗就会出现。

是否必现:
是

脚本软件版本：
0.1.49以后的版本

windows操作系统:
 Windows 11 Pro 23H2 22631.3593

**Comment by ok-oldking** [comment]
试试[v0.1.55](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.1.55)
