### ISSUE TITLE
[BUG]月卡检测功能无效

### ISSUE THREAD

**Issue by leohoo633** [ok-oldking/ok-wuthering-waves#42]
描述错误:
开启检测小月卡功能，设置本机时间凌晨4点，但是第二天一早起来还是卡在月卡界面。在此之前已按照Q&A清单检查了设置。

复现步骤 按照以下步骤复现行为：
N/A

截图 :
暂无

是否必现:
大概率

录屏:
暂无

脚本软件版本：
v.0.1.47

windows操作系统:
Windows 10 家庭中文版 22H2 19045.3693

上传日志:
[logs.zip](https://github.com/user-attachments/files/16408568/logs.zip)

感谢作者大大勤恳更新！另外希望加入大世界战斗结束后视角转动或者转圈跑的操作来提升声骸捡取准确度。

**Comment by leohoo633** [comment]
另，实测.55版本实装的F9快捷键无效。感谢作者大大高速更新，太牛了

**Comment by ok-oldking** [comment]
试试最新版
