### ISSUE TITLE
[BUG] 无法启动，一直等待，60秒过去了依然等待

### ISSUE THREAD

**Issue by sumght-z** [ok-oldking/ok-wuthering-waves#43]
描述错误:
无法启动，一直等待，60秒过去了依然等待

复现步骤 按照以下步骤复现行为：

1. 点击 ‘任何开始脚本的功能，甚至是诊断问题按钮’
2. 就显示正在启动，60秒后超时，直到0都还是没开始

截图 :
![6d9f084da68a6e25033ccc50cbf3d6c7](https://github.com/user-attachments/assets/f144acf4-df24-44ba-a0ad-e8090dc36371)

是否必现:
是

脚本软件版本：
使用过0.1.54，现在是0.1.56

windows操作系统:
图中自带，winserver 2019

上传日志:
将脚本安装目录的logs,screenshots打包上传附件
[ok-ww.zip](https://github.com/user-attachments/files/16410606/ok-ww.zip)

**Comment by ok-oldking** [comment]
管理员运行试试

**Comment by sumght-z** [comment]
已管理员运行，依然同样的问题
![QQ_1722250779752](https://github.com/user-attachments/assets/67dd0c77-18a6-4d76-b302-c3a418b2eff7)
[logs.zip](https://github.com/user-attachments/files/16411657/logs.zip)

**Comment by ok-oldking** [comment]
C:\Users\sumght\Wuthering Waves\Wuthering Waves Game\Client\Binaries\Win64\Client-Win64-Shipping.exe
 看看这个文件是否存在, 有没有装过多个游戏客户端?

**Comment by ok-oldking** [comment]
[Release v0.1.58](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.1.58)
