### ISSUE TITLE
EN Support 

### ISSUE THREAD

**Issue by shadowblade238** [ok-oldking/ok-wuthering-waves#48]
Please add more EN instructions  I dont know which programs I need to donwload and most of the text  is in chinese

**Comment by ok-oldking** [comment]
read the How to Run in Readme

**Comment by shadowblade238** [comment]
> read the How to Run in Readme

And what is   error  (must be in game world and in teams)
Im in game  world and I got this error

**Comment by ok-oldking** [comment]
I have update the en readme, you can check out the FAQ part
