### ISSUE TITLE
[REQUEST] 能否增加忽略关闭HDR的选项？

### ISSUE THREAD

**Issue by razormax007** [ok-oldking/ok-wuthering-waves#5]
建议:
之前HDR模式下用得挺舒服的，虽然我知道开启会影响精确度。
但是还是希望作者大大可以增加一个忽略关闭的选项，谢谢！
另外弱弱问一下作者之后会不会添加丹瑾自动战斗的支持？

**Comment by ok-oldking** [comment]
不是特别好添加, 你下载源码直接跑 注释下代码吧, 丹瑾没计划, 你要有兴趣可以自己加下

**Comment by ok-oldking** [comment]
Release v0.1.64
