### ISSUE TITLE
[BUG]刷摩托车剩一丝血 后会停止攻击，之后会进行四方向检测 

### ISSUE THREAD

**Issue by fuyn101** [ok-oldking/ok-wuthering-waves#50]
请先挨个检查,[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

描述错误:
刷摩托车剩一丝血 后会停止攻击，之后会进行四方向检测 

复现步骤 按照以下步骤复现行为：

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
暂无截图 观察到会编辑上去

是否必现:
小概率

录屏:
无

脚本软件版本：
v0.1.71

windows操作系统:
Windows 11 Pro 23H2 22631.3672

上传日志:
将脚本安装目录的logs,screenshots打包上传附件
[ok-ww.zip](https://github.com/user-attachments/files/16476245/ok-ww.zip)

**Comment by ok-oldking** [comment]
用1.70版本, 脱战会截图上传下看看

**Comment by ok-oldking** [comment]
[Release v0.2.1](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.2.1)
