### ISSUE TITLE
[BUG]出现boss没打完脱战问题

### ISSUE THREAD

**Issue by Caijizhi** [ok-oldking/ok-wuthering-waves#52]
请先挨个检查,[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

描述错误:
刷到第五次出现boss没打完脱战问题

复现步骤 按照以下步骤复现行为：

刷到第五次出现boss没打完脱战问题

截图 :
无截图，有录屏

是否必现:
大概率

录屏:
有录屏，日志和录屏的压缩文件发在日常闲聊频道里（bug反馈频道只读）

脚本软件版本：
[如]0.1.71

windows操作系统:
[例如] Windows 10

上传日志:
将脚本安装目录的logs,screenshots打包上传附件

**Comment by ok-oldking** [comment]
用1.70 出现问题上传
