### ISSUE TITLE
[BUG]今汐有时不喷E4

### ISSUE THREAD

**Issue by B1ngFeng** [ok-oldking/ok-wuthering-waves#53]
请先挨个检查,[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

描述错误:
打深渊中二，今汐+维里奈+渊武，好几次今汐都没喷出来E4。
我看着的情况是有时候光来回切角色了，E4都亮了但是没点，甚至韶光已经满了，结果到状态没了也没喷，又得重新打E2。
而且一直并没有被怪打断过，所以不知道为什么没连上招。
以及，有时候喷E4的前一秒Q好了但是没放，直接E4了。
（感谢作者辛勤更新，昨天我用来刷角的声骸很好用）

复现步骤：
1. 打开“实时触发”中的“自动战斗”
2. 进深渊，F开始
3. 看到错误，今汐有时喷不出E4

截图 :
无

是否必现:
大概率

录屏:
无

脚本软件版本：
0.1.71（最新）

windows操作系统:
Windows 10 专业版 22H2 19045.3393

上传日志:
将脚本安装目录的logs,screenshots打包上传附件
screenshots里只有一个通关显示星数时的02-24-51.334_click_resonance too long, breaking_original.png，上传了logs里的两个txt文件。
看2:30往前的两把，都是中二塔，再之前2:00左右的时候也是有时不喷，不过那时是我改了画质文件，再开脚本画面会卡，不知道有没有影响，2:30之前的两把是把画质文件改回来了原本的，画面没有卡顿了，一直1080P 60帧稳定。（改画质文件前后，我打完之后点软件里的“诊断问题”，截图FPS都是12~13，这正常吗）
[ok-script.log](https://github.com/user-attachments/files/16482527/ok-script.log)
[ok-script_error.log](https://github.com/user-attachments/files/16482528/ok-script_error.log)

**Comment by ZstarsK** [comment]
我渊武的E也经常不放， 是因为没有70级吗。。

**Comment by ok-oldking** [comment]
只有中二塔才会吗? 我还没打到

**Comment by i-kanyu** [comment]
感觉有点像第一次因为受击被打断了，然后再次切的时候脚本没认为他可以喷，从头叠了..

**Comment by ZstarsK** [comment]
> 只有中二塔才会吗? 我还没打到

不止中二 左4也是。 应该不是我一个人的问题， 我看频道里也有反馈。
两个问题
1、渊武40级不插E， 我不知道和等级有没有关系
2、今汐很少喷

系统Win10 22H2.  必要可以联系提供log

**Comment by ok-oldking** [comment]
试试 [Release v0.1.88](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.1.88) Pre-release

**Comment by ZstarsK** [comment]
还是不喷
渊武还是不插E

**Comment by ZstarsK** [comment]
> 试试 [Release v0.1.88](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.1.88) Pre-release

v0.1.88
还是不喷
渊武还是不插E

**Comment by ZstarsK** [comment]
> 试试 [Release v0.1.88](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.1.88) Pre-release

配吟霖好像稍微正常一点， 大多能喷出来
配渊武打中1， 开局40秒之后才喷第一下
