### ISSUE TITLE
内存溢出问题

### ISSUE THREAD

**Issue by Fujiwara-no-Mokou** [ok-oldking/ok-wuthering-waves#55]
请先挨个检查,[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

描述错误:
内存溢出，脚本报错，游戏闪退

复现步骤 按照以下步骤复现行为：

正常跑脚本就会出现问题，稳定复现
PC配置：i5 12490f;  6750xt; 3200hz 48g内存; 

截图 :
![QQ图片20240805121737](https://github.com/user-attachments/assets/6955993a-fb6f-4d07-9257-5eb0ec575fd3)
![QQ图片20240805121716](https://github.com/user-attachments/assets/567b1d5c-182d-4d4d-aca1-08b37d6ade8d)

是否必现:
是

录屏:
暂无录屏

脚本软件版本：
0.1.75

windows操作系统:
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2024/‎3/‎25
操作系统内部版本	19045.4651
体验	Windows Feature Experience Pack 1000.19060.1000.0

上传日志:
[logs.zip](https://github.com/user-attachments/files/16490649/logs.zip)

**Comment by ok-oldking** [comment]
更新最新
