### ISSUE TITLE
[逻辑改进]关于渊武不放E

### ISSUE THREAD

**Issue by zIIImRASAKI** [ok-oldking/ok-wuthering-waves#58]
请先挨个检查,[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

描述错误:
今汐+渊武+维里奈（渊武4C带的龟龟）  渊武会切出来普攻 大招 但是不会原地插E柱子
感觉渊武E的cd本身就短，可以额外加一下逻辑吗
看QQ频道里好几个人在问为什么渊武不插E，一直没人解答，不清楚是本身逻辑就这样还是PC环境不同个人差
今汐和维里奈的逻辑没问题

是否必现:
是

脚本软件版本：
0.1.77正式版

windows操作系统:
Windows 11

**Comment by ok-oldking** [comment]
要70级 自动插E
