### ISSUE TITLE
[BUG]前端显示BUG

### ISSUE THREAD

**Issue by hyz-hyz** [ok-oldking/ok-wuthering-waves#59]
有一个前端显示BUG（不影响正常使用），希望有空的时候能修复一下，新功能声骸五合一的配置下拉菜单中，点开后页面不会恢复，通常的逻辑应该是点击下拉后展示可配置项，完成后再次点击恢复隐藏，其他功能是正常的，目前这个BUG从新功能首次上线后到现在的v0.1.80依然存在，附上问题截图，图1为正常逻辑，图2为BUG
![屏幕截图 2024-08-06 034338](https://github.com/user-attachments/assets/ba1acb58-7be3-4f3a-9aa1-4a5b1cb885e2)
![屏幕截图 2024-08-06 034121](https://github.com/user-attachments/assets/eb74c099-c98b-4655-aaef-e55ae58c1957)

**Comment by ok-oldking** [comment]
[Release v0.1.81](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.1.81)
