### ISSUE TITLE
[BUG]加载时间长时会退出程序

### ISSUE THREAD

**Issue by Master-Tan** [ok-oldking/ok-wuthering-waves#61]
请先挨个检查,[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

描述错误:
游戏跳转加载时间长时会退出刷取程序

复现步骤 按照以下步骤复现行为：

1. 开始刷取声骸（角/大世界boss）
2. 自动点击进入副本跳转/信标跳转进度读条
3. 读条加载进度慢时触发ok.task.TaskExecutor.WaitFailedException退出刷取

- 建议：作者大大：能不能把time_out作为一个可选的参数放在交互页面中使用户能根据电脑性能自己调节time_out的时间？（本人学生党，电脑配置不太好但还是很喜欢鸣潮，有时候进入副本/退出副本/大世界信标跳转都需要比较久的读条时间，导致刷取程序总是触发超时退出 (T ^ T) (T ^ T) 

截图 :
无

是否必现:
是

录屏:
暂无

脚本软件版本：
最新

windows操作系统:
Win10

上传日志:
将脚本安装目录的logs,screenshots打包上传附件
[ok-script.log](https://github.com/user-attachments/files/16514616/ok-script.log)
[ok-script_error.log](https://github.com/user-attachments/files/16514618/ok-script_error.log)

**Comment by ok-oldking** [comment]
下个版本加一下 现在30有点低
