### ISSUE TITLE
[SUPPORT]希望添加一个"交互(拾取)"的自定义按键

### ISSUE THREAD

**Issue by i12cu84** [ok-oldking/ok-wuthering-waves#62]
up的项目很给力很好使!
不过我键位有将交互拾取的"F"键改成了"E"(其他技能键有了不赘述
希望up有空可以加上一个,感谢!

**Comment by ok-oldking** [comment]
拾取使用图片识别 加不了

**Comment by i12cu84** [comment]
将"self.send_key('f')"的'f'改成"可定义的按键"是不可行的嘛,(没咋用python不明白
