### ISSUE TITLE
[BUG]1.91大世界自动战斗异常

### ISSUE THREAD

**Issue by johnson50313** [ok-oldking/ok-wuthering-waves#64]
描述错误:
版本更新后才出现，大世界自动战斗判断异常，没有任何敌方单位，却一直维持战斗模式

录屏:
https://github.com/user-attachments/assets/d26e3520-2477-48bc-9650-cad46d828f6a

脚本软件版本：
1.91

windows操作系统:
Windows 10

上传日志:
[logs.zip](https://github.com/user-attachments/files/16568602/logs.zip)

**Comment by ok-oldking** [comment]
录屏不完整
