### ISSUE TITLE
添加运行时音量合成器静音选项

### ISSUE THREAD

**Issue by lingkai5wu** [ok-oldking/ok-wuthering-waves#66]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement)

描述:在实时触发或其他位置添加运行时将游戏音量合成器静音选项。
[可参考](https://github.com/lingkai5wu/AutoMuteBG/blob/master/utils/AudioUtil.py)

**Comment by ok-oldking** [comment]
[v0.1.92](https://github.com/ok-oldking/ok-wuthering-waves/tree/v0.1.92)
