### ISSUE TITLE
[BUG]0.1.7和0.1.9今汐戰鬥BUG

### ISSUE THREAD

**Issue by alvis333** [ok-oldking/ok-wuthering-waves#7]
使用今汐跑4CBOSS会发生问题 今汐只要使用强化E之后会判定打完BOSS 然后直接开地图传到下个BOSS点

**Comment by alvis333** [comment]
目前测试今汐打角能正常运行 只有大世界4C会翻车

**Comment by ok-oldking** [comment]
看下常见问题hdr那一条 是不是开了滤镜

**Comment by alvis333** [comment]
windows的护眼和HDR都没有开 想请问会不会是ROG armoury crate的gamevisual导致的  如果是的话要怎么关闭呢

**Comment by ok-oldking** [comment]
不太清楚, 你截图测试一下, 如果技能图标不是纯白的255,255,255 就是有改颜色

**Comment by alvis333** [comment]
目前更新到最新版依然存在问题 应该是我自己的颜色被改了 想请问截图测试要截强化e的图标还是一般状态的e就可以 截图之后要怎么测试技能图标示不是255.255.255呢

**Comment by alvis333** [comment]
用网页测试了一下图标 是255 255 255没错 应该是今汐出问题? 只有今汐会强化e之后直接开始走路 然后就开地图传送了 其他角色实测一整晚都没问题
![Uploading 螢幕擷取畫面 2024-07-18 182728.png…]()

**Comment by ok-oldking** [comment]
12版本吗. 关于里面点检查更新

**Comment by alvis333** [comment]
对的 我是12

**Comment by ok-oldking** [comment]
试试游戏视频设置 改成默认的

**Comment by alvis333** [comment]
![螢幕擷取畫面 2024-07-18 222146](https://github.com/user-attachments/assets/0a8bfcda-f91b-4722-97db-e85c64472071)
![螢幕擷取畫面 2024-07-18 222158](https://github.com/user-attachments/assets/84c9dbb6-6862-4d0c-a4c8-a7319faa27a7)
![螢幕擷取畫面 2024-07-18 222207](https://github.com/user-attachments/assets/e694862b-722c-4377-865f-6cfeb67c78ae)
哪些需要更改吗

**Comment by ok-oldking** [comment]
你这个情况比较难查, 换个分辨率试试. 如果你懂python的话,本地调试下

**Comment by alvis333** [comment]
分辨率调成中也没有解决 可能无解了哈哈

**Comment by ok-oldking** [comment]
可能是开了显卡滤镜或者锐化之类 你查查

**Comment by alvis333** [comment]
好奇为何只有今汐受影响 我是rog的 不知道是不是他的自带滤镜导致的 只知道我滤镜是用他预设的

**Comment by ok-oldking** [comment]
试试 [Release v0.1.65](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.1.65)

**Comment by alvis333** [comment]
更新之后传到王位置就直接停止运行 连自动战斗也不行了 问题更严重了
![螢幕擷取畫面 2024-08-01 003431](https://github.com/user-attachments/assets/fe9fb7a0-92fa-455d-afb8-0cb984c4df59)

**Comment by ok-oldking** [comment]
[Release v0.1.66](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.1.66)

**Comment by alvis333** [comment]
真好奇为啥只有我这样

**Comment by ok-oldking** [comment]
今汐不会强化e的问题解决了吗

**Comment by alvis333** [comment]
他一直都会放强化e 1.65是无法进入4c战斗和自动战斗 1.66后可以了 但是他问题跟之前一样 强化e放完就不会继续打了

**Comment by alvis333** [comment]
好像是放完强化e就直接判定打死boss了
