### ISSUE TITLE
四方向搜索失效

### ISSUE THREAD

**Issue by Fujiwara-no-Mokou** [ok-oldking/ok-wuthering-waves#70]
四方向搜索失效，不知道是不是1.2之后更改了鼠标中键锁定的逻辑，实际上转向不生效

是否必现:
必现

录屏:
最好有录屏上传QQ频道

脚本软件版本：
0.1.97

**Comment by ok-oldking** [comment]
鼠标中键要能转向才行, 改成默认的

**Comment by B1ngFeng** [comment]
> 鼠标中键要能转向才行, 改成默认的

是要在改快捷键那里的[目标选择和切换]里选第2种吗？在README和软件里也注明一下吧？
