### ISSUE TITLE
[Enhancement] 软件生态：检查更新部分

### ISSUE THREAD

**Issue by BUAAkang** [ok-oldking/ok-wuthering-waves#74]
![image](https://github.com/user-attachments/assets/07f59b76-0862-4882-8e21-7dcd724b4f26)
点击之后上方会出现一个下载进度条，结束后会提示更新
![image](https://github.com/user-attachments/assets/03b10fcd-c9b6-455a-96c1-0cca257cb161)
但是很可惜点击之后不会出现任何反应。我的更新引导包在哪里，或者zip文件下载到了哪里，不得而知。
望尽快优化。既然是一个更新如此频繁的软件，更新生态应该更完备一点，逐版本下载zip也太过于。。。

**Comment by B1ngFeng** [comment]
现在加了新的更新方式，估计就是旧的换到新的的时候有问题，我新版更新新版是没问题的，旧版更新新版就手动更新一下吧，在updates文件夹里的最新版本里复制所有的东西到主目录里就行了

**Comment by BUAAkang** [comment]
好的，望越做越好！：）
