### ISSUE TITLE
[BUG]今汐e4不喷，e2不放，存在无意义切人

### ISSUE THREAD

**Issue by qwe4559999** [ok-oldking/ok-wuthering-waves#80]
描述错误:
今汐e4不喷，e2不放，存在无意义切人，配队今吟白

复现步骤 按照以下步骤复现行为：

1. 开启自动战斗，进入深塔左四
2. 吟霖主声骸带的是游麟机枢
3. 看到错误

是否必现:
是

录屏:
录屏已上传QQ频道

脚本软件版本：
0.2.3

windows操作系统:
Windows 11 家庭中文版 23H2 22631.4037

上传日志:

[rizhi.zip](https://github.com/user-attachments/files/16647319/rizhi.zip)

**Comment by qwe4559999** [comment]
感谢作者及时解决问题，该issue结束

**Comment by ok-oldking** [comment]
试试最新版

**Comment by qwe4559999** [comment]
已经解决了，感谢
