### ISSUE TITLE
[BUG]还是版本更新，但看似是重启路径设置有问题

### ISSUE THREAD

**Issue by BUAAkang** [ok-oldking/ok-wuthering-waves#82]
描述错误:
OK Updater出现问题

复现步骤 按照以下步骤复现行为：

1. 点击 ‘更新到XXX版本’
2. 弹出OK Updater
3. 看到错误

截图 :
![image](https://github.com/user-attachments/assets/999396c3-6c85-4ac2-b9ba-9037da70f9ba)

是否必现:
尚不确定，可能是路径解析有问题

脚本软件版本：
V0.99.0
OS：windows11 Professional

**Comment by BUAAkang** [comment]
注：还是更新成功了的，但是重启出问题

**Comment by ok-oldking** [comment]
最新版试试
