### ISSUE TITLE
[BUG]刷副本BOSS声骸游戏自动退出（UE4 Fatel error）

### ISSUE THREAD

**Issue by qwe4559999** [ok-oldking/ok-wuthering-waves#84]
描述错误:
刷副本BOSS声骸达5h左右，游戏自动退出（虚幻4 Fatel error）

复现步骤 按照以下步骤复现行为：

1.点击刷副本BOSS声骸，开启无妄者副本
2. 后台挂机5h
3. 看到错误

截图 :
如果适用，添加截图以帮助解释您的问题。
![屏幕截图 2024-08-19 205042](https://github.com/user-attachments/assets/633a981a-7239-4c2e-ba1d-426b97e4f9c9)

是否必现:
是

录屏:
无

脚本软件版本：
0.2.8

windows操作系统:
Windows 11 家庭中文版 23H2 22631.4037

上传日志:
[ok-ww.zip](https://github.com/user-attachments/files/16660446/ok-ww.zip)

**Comment by qwe4559999** [comment]
早上发现是虚幻4崩了导致的游戏退出，是CPU/显卡占用太高了吗

**Comment by jerrytang123** [comment]
同样问题

**Comment by Mmmomentum** [comment]
我也遇到类似的游戏退出问题，大约是四个半小时左右，游戏消失。人不在电脑前所以不太确定是UE4 error，但游戏退出的时长是差不多的。
