### ISSUE TITLE
[Enhancement]希望添加循环凹深渊满星

### ISSUE THREAD

**Issue by dong-jpg** [ok-oldking/ok-wuthering-waves#89]
描述:目前其实大部分人的配队在运气好的情况下可以满星，但是需要凹多次，希望可以添加一个循环凹深渊的自动任务，可以由用户选择好配队之后开始自动刷，深渊的重复步骤也比较简单：
1.点击开始挑战，进入场景，角色前进直到识别到开始按钮
2.自动战斗
3.战斗结束出现星级，如果不是三星则重新挑战，如果满星则点击下一层。
4.大部分人奶都不够，可能会前三关的时候上两人队，第四关才上奶，可以加个第四关的时候自动给配队加上奶位

**Comment by ok-oldking** [comment]
没计划
