### ISSUE TITLE
[BUG] 刷出声骸后不会移动视角寻找，只能往前走一下退出

### ISSUE THREAD

**Issue by shimw6828** [ok-oldking/ok-wuthering-waves#9]
描述错误:
刷出声骸后不会移动视角寻找，只能往前走一下退出
具体来说，我刷光鸟的时候，打死之后安可又放了一下技能往前跳了一段距离，光鸟的声骸在人物身后。此时，正常逻辑应该是移动视角寻找声骸，但是只是往前走了两步，然后就去下一个boss了。是否能够改进一下这个打完之后声骸的搜寻方法。
https://github.com/lazydog28/mc_auto_boss
比如这个脚本中声骸打完之后会90度切换视角搜寻声骸位置，我觉得很有参考的价值

脚本软件版本：
v0.1.9

windows操作系统:
Windows 11 Pro 23H2 22631.3593

**Comment by lin-xiaosheng** [comment]
+1，目前打角之类的位移大的BOSS，没有旋转视角的话，找不到声骸的概率比较高

**Comment by shimw6828** [comment]
已收到！非常感谢您的支持

**Comment by ok-oldking** [comment]
[Release v0.1.69](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.1.69)
