### ISSUE TITLE
[BUG]启动ok-ww时出现pickle.UnpicklingError

### ISSUE THREAD

**Issue by qwe4559999** [ok-oldking/ok-wuthering-waves#90]
描述错误:
启动ok-ww时出现pickle.UnpicklingError

复现步骤 按照以下步骤复现行为：

1. 下载ok--ww的release包
2. 解压后双击exe
3. 看到错误

截图 ：
![db7b5432035d230a945994957130b22b](https://github.com/user-attachments/assets/5db5ffd0-e4fd-4d03-a132-a9a7f21d257e)

是否必现:
小概率，只有个别用户出现，可通过新建一个windows账户解决

脚本软件版本：
0.2.8

windows操作系统:
windows10 22H2

上传日志:
[ok-script_error.log](https://github.com/user-attachments/files/16710630/ok-script_error.log)

[ok-script.log](https://github.com/user-attachments/files/16710631/ok-script.log)

**Comment by ok-oldking** [comment]
看看常见问题

**Comment by qwe4559999** [comment]
常见问题的解决方法都试过了。但这是极个别人出现的问题，换一下Windows账户就可以解决了

**Comment by qwe4559999** [comment]
嗯..这是频道里面某个人遇到的问题。我自己也复现不了，那就先不管了
