### ISSUE TITLE
[BUG]错误的时机下，月卡检测不断地进行截图

### ISSUE THREAD

**Issue by Mmmomentum** [ok-oldking/ok-wuthering-waves#91]
描述错误:

凌晨4点整，工具不断重复截图操作，从截图的名称判断应该是在判断小月卡是否存在，但是一直停留在了无妄者等级选择界面，该界面是不会弹窗月卡的。

复现步骤 按照以下步骤复现行为：

1. 设置工具凌晨4点检测小月卡
2. 在4点之前进入无妄者等级选择界面等待
3. 等到时间到达4点触发月卡检测，由于该界面不弹窗月卡，工具一直截图

截图 :
screenshots里每秒截图一张，由于数量太多文件较大，我当时停止工具后全部清除了，暂时没法提供截图

是否必现:
大概率

脚本软件版本：
0.2.8

windows操作系统:
Windows 11 专业版 23H2 22631.4037

上传日志:
[logs.zip](https://github.com/user-attachments/files/16721479/logs.zip)

**Comment by ok-oldking** [comment]
[Release v0.2.9](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.2.9)
如果弹不出来的话 估计只能大世界boss跳月卡

**Comment by Mmmomentum** [comment]
能不能改成：截图没截到月卡就继续执行脚本，十几秒后再次截图检测月卡，多次重复以后实在没检测到就放弃检测月卡，继续执行脚本。
