### ISSUE TITLE
[BUG]突然打不开显示的界面，但是后台显示进程在运行

### ISSUE THREAD

**Issue by heibian** [ok-oldking/ok-wuthering-waves#94]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=)

描述错误:
[请清晰简洁地描述错误是什么]

复现步骤 按照以下步骤复现行为：

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
如果适用，添加截图以帮助解释您的问题。

是否必现:
是/否/大概率/小概率

录屏:
最好有录屏上传QQ频道

脚本软件版本：
[如]1.1.1

windows操作系统:
[例如] Windows 11 Pro 23H2 22631.3593

上传日志:
将脚本安装目录的logs,screenshots打包上传附件

**Comment by qwe4559999** [comment]
我也遇到了相同的问题，通过卸载ok-ww然后重装即可解决问题

**Comment by qwe4559999** [comment]
另外，还请写出详细的问题描述以便开发者理解您的问题

**Comment by ok-oldking** [comment]
结束任务 再开不行吗 ?

**Comment by qwe4559999** [comment]
> 结束任务 再开不行吗 ?

情况是这样:双击ok-ww.exe无反应，也不会有任何窗口出现。如果多双击几次可以看到任务管理器内有多个ok-ww进程在运行，但看不到窗口弹出

**Comment by qwe4559999** [comment]
> 结束任务 再开不行吗 ?

另外，通过任务管理器结束任务重新打开ok-ww或者重启电脑再重新打开都是无效的，只能通过彻底删除以后再重新装一个

**Comment by ok-oldking** [comment]
上传日志看看

**Comment by qwe4559999** [comment]
[logs.zip](https://github.com/user-attachments/files/16738023/logs.zip)
是8月24日晚十点多左右遇到的问题，查看该时段的日志即可，麻烦了

**Comment by 1207877136** [comment]
我也遇到了同样的问题，蹲一个解决方法

**Comment by 1207877136** [comment]
> 我也遇到了同样的问题，蹲一个解决方法

解决了貌似，好像就是单纯启动慢，我双击ok-ww之后十分钟后才显示出窗口

**Comment by tommytroylin** [comment]
0.3.54我这边也能复现。windows 11。
第一次打开没问题。包括安装依赖5个g。只要关闭窗口就再也打不开了。任务管理器里看不到进程。也没有日志和弹窗。
每次都得整个删除+重新解压安装。
我换回0.2.17就没问题

**Comment by ok-oldking** [comment]
> 0.3.54我这边也能复现。windows 11。 第一次打开没问题。包括安装依赖5个g。只要关闭窗口就再也打不开了。任务管理器里看不到进程。也没有日志和弹窗。 每次都得整个删除+重新解压安装。 我换回0.2.17就没问题

试试0.3.55

**Comment by tommytroylin** [comment]
> > 0.3.54我这边也能复现。windows 11。 第一次打开没问题。包括安装依赖5个g。只要关闭窗口就再也打不开了。任务管理器里看不到进程。也没有日志和弹窗。 每次都得整个删除+重新解压安装。 我换回0.2.17就没问题
> 
> 试试0.3.55

已确认修复~
