### ISSUE TITLE
[Enhancement]深坠异想奇境自动战斗

### ISSUE THREAD

**Issue by link-fgfgui** [ok-oldking/ok-wuthering-waves#95]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=label%3Aenhancement)

描述:
单人自动放技能,深坠异想奇境自动战斗(不需要关卡自动化,支持一下单人自动战斗就行)

**Comment by ok-oldking** [comment]
支持不了 不太一样
