### ISSUE TITLE
[BUG]每日活跃没做完时，刷4C声骸在F2界面点不到boss

### ISSUE THREAD

**Issue by B1ngFeng** [ok-oldking/ok-wuthering-waves#98]
描述错误:
每日活跃没做完时，刷4C声骸在F2界面点不到boss

复现步骤 按照以下步骤复现行为：
1. 刷大世界4C boss声骸
2. 看到错误

是否必现:
是

脚本软件版本：
0.2.9

windows操作系统:
Windows 10 专业版 22H2 19045.3393

上传日志:
最后，试了好几次
[ok-script.log](https://github.com/user-attachments/files/16738510/ok-script.log)

**Comment by B1ngFeng** [comment]
还是说分辨率的问题？我是打开软件之后把游戏从1080P全屏调成720P窗口的。如果是这个问题的话，那就加一个每次开始任务的时候判断一下分辨率？
还是说我加了画质修改mod的问题？我试了一下，调成窗口720P，开始任务，结果现在提示无法F2，我游戏里也是大世界里快捷键esc、F2都用不了，不知道为什么。
我又试了一下，全屏打开游戏，然后打开软件，直接开始任务，是可以的。

**Comment by ok-oldking** [comment]
[Release v0.2.10](https://github.com/ok-oldking/ok-wuthering-waves/releases/tag/v0.2.10)
