### ISSUE TITLE
[BUG]更新到最新版后打不开程序

### ISSUE THREAD

**Issue by zxygzxy** [ok-oldking/ok-wuthering-waves#99]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=)

描述错误:如图打不开程序
[请清晰简洁地描述错误是什么]

复现步骤 按照以下步骤复现行为：

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
如果适用，添加截图以帮助解释您的问题。

是否必现:
是/否/大概率/小概率

录屏:
最好有录屏上传QQ频道

脚本软件版本：v0.2.9（没记错的话，反正是最新的）
[如]1.1.1 

windows操作系统:版本	Windows 11 家庭中文版	22631.4037
![QQ截图20240825132543](https://github.com/user-attachments/assets/dbb0809c-e654-4cda-96a0-a86308bb2f88)

体验	Windows Feature Experience Pack 1000.22700.1027.0

[例如] Windows 11 Pro 23H2 22631.3593

上传日志:
将脚本安装目录的logs,screenshots打包上传附件

**Comment by zxygzxy** [comment]
不确定是不是没安python的事，一会我安个python再试试

**Comment by zxygzxy** [comment]
log文件忘传了
[logs.zip](https://github.com/user-attachments/files/16739132/logs.zip)

**Comment by ok-oldking** [comment]
杀毒软件 常见问题

**Comment by zxygzxy** [comment]
我电脑就装了火绒和联想自带的电脑管家，关了之后还是不行
